name: Deploy brand/ to website.com/brand (keep root intact)

on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: website-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install deps (brand/)
        working-directory: brand
        run: npm i

      # Build for /brand (custom-domain subpath)
      - name: Build brand with correct base
        working-directory: brand
        run: npx vite build --base=/brand/

      # Assemble publish/ = (current root mirror) + (fresh /brand)
      - name: Prepare publish directory
        run: mkdir -p publish

      # Mirror the current production root so we DON'T overwrite homepage.
      # If your site blocks bots, this may pull a minimal copy; it's still safer than wiping root.
      - name: Mirror current website.com root into publish/
        run: |
          apt-get update && apt-get install -y wget > /dev/null
          wget -q -e robots=off --no-parent --adjust-extension --convert-links --page-requisites \
               --no-host-directories --directory-prefix=publish \
               https://website.com/ || true

      # Drop our new brand app under /brand
      - name: Place brand under /brand
        run: |
          rm -rf publish/brand
          mkdir -p publish/brand
          cp -R brand/dist/* publish/brand/

      # Keep custom domain + Pages quirks
      - name: Add CNAME and .nojekyll
        run: |
          echo "website.com" > publish/CNAME
          touch publish/.nojekyll

      # Guard: ensure brand bundles exist and point to /brand/assets
      - name: Verify brand build paths
        run: |
          ls -la publish/brand/assets || (echo "❌ No brand bundles"; exit 1)
          if ! grep -Eq 'src="/brand/assets/.*\.js"' publish/brand/index.html; then
            echo "❌ publish/brand/index.html does not reference /brand/assets/*.js"
            sed -n '1,120p' publish/brand/index.html || true
            exit 1
          fi
          if grep -q '/src/main\.tsx' publish/brand/index.html; then
            echo "❌ dev HTML leaked into brand build"
            exit 1
          fi
          echo "✅ brand paths OK"

      - name: Upload Pages artifact (root + /brand)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
